name: chat_app
description: "A new Flutter project."


publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.8
  go_router: ^15.1.2
  supabase_flutter: ^2.9.1
  fpdart: ^1.1.1
  flutter_bloc: ^9.1.1
  get_it: ^8.0.3
  connectivity_plus: ^6.1.4
  uuid: ^4.5.1
  crypto: ^3.0.6
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^5.0.0

flutter:
  
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
